baseurl = "http://localhost:1313"
title = "Aiman Zafry"

[menus]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "hello"
  [params.author]
    name = "Aiman Alzafry"  # Website and RSS feed author
    job = "3D Generalist / Scriptwriter"
    email = "aiman.zafry@outlook.com"  # RSS feed email address

[[params.highlight]]
key = 0
page = "emoji-support"

[[params.highlight]]
key = 1
page = "migrate-from-jekyll"

[[params.highlight]]
key = 2
page = "rich-content"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/gohugoio"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.example.com"
aria = "LinkedIn Profile"

[[params.social]]
key = 2
name = "email"
url = "mailto:email@example.com"
aria = "My e-Mail Address"

