baseurl = "http://localhost:1313"
title = "Aiman Zafry"

[module]
  [module.hugoVersion]
    min = "0.134.2"

[menus]
  [[menu.header]]
    name = "Animations"
    weight = 1
    params = { Img = "/img/cat/reel.svg" }
    url = "anim"
  [[menu.header]]
    name = "Projects"
    weight = 5
    params = { Img = "/img/cat/apple.svg" }
    url = "proj"
  [[menu.header]]
    name = "Notes"
    weight = 10
    params = { Img = "/img/cat/book.svg" }
    url = "notes"

[params]
  [params.author]
    name = "Aiman Alzafry"  # Website and RSS feed author
    job = "3D Artist"
    email = "aiman.zafry@outlook.com"  # RSS feed email address

[[params.highlight]]
key = 0
page = "ScrewUp"

[[params.highlight]]
key = 1
page = "WarHammer"

[[params.highlight]]
key = 2
page = "Precipes"

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/azulconspirator"
target = "_blank"
aria = "GitHub Profile"
falogo= "fa-brands fa-github"

[[params.social]]
key = 2
name = "Instagram"
url = "https://www.instagram.com/acelz_artistry/"
target = "_blank"
aria = "Instagram"
falogo= "fa-brands fa-instagram"

[[params.social]]
key = 0
name = "Resume"
url = "/resume"
target = "_blank"
aria = ""
falogo= "fa-solid fa-address-card"

[[params.social]]
key = 2
name = "Email"
url = "mailto:aiman.zafry@outlook.com"
aria = "My e-Mail Address"
falogo= "fa-regular fa-envelope"

[markup.goldmark.parser.attribute]
block = true # default is false

