baseurl = "http://localhost:1313"
title = "Aiman Zafry"

[module]
  [module.hugoVersion]
    min = "0.114.0"

[params.style]
color = 'red'

[menus]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "hello"
  [params.author]
    name = "Aiman Alzafry"  # Website and RSS feed author
    job = "3D Generalist"
    email = "aiman.zafry@outlook.com"  # RSS feed email address

[[params.highlight]]
key = 0
page = "Precipes"

[[params.highlight]]
key = 1
page = "ScrewUp"

[[params.highlight]]
key = 2
page = "WarHammer"

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/azulconspirator"
target = "_blank"
aria = "GitHub Profile"

[[params.social]]
key = 2
name = "Instagram"
url = "https://www.instagram.com/acelz_artistry/"
aria = "Instagram"

[[params.social]]
key = 2
name = "Email"
url = "mailto:aiman.zafry@outlook.com"
aria = "My e-Mail Address"

