baseURL = 'https://zypherconspirator.github.io/'
languageCode = 'en-us'
title = 'LzyBones Portfolio'

[params.detail]
name_1 = 'Lzy'
name_2 = 'Bones'
career = '3D Artist'

[params.openforhire]
isOpen = true

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/azulconspirator"
target = "_blank"
aria = "GitHub Profile"
falogo= "fa-brands fa-github"

[[params.social]]
key = 2
name = "Instagram"
url = "https://www.instagram.com/lazy.sketchy/"
target = "_blank"
aria = "Instagram"
falogo= "fa-brands fa-instagram"

[[params.social]]
key = 2
name = "Email"
url = "mailto:lazy.sketchy@gmail.com"
aria = "My e-Mail Address"
falogo= "fa-solid fa-envelope"

[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true 

[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]